apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k3supdater

resources:
- namespace.yml
- cronjob.yml

# Needs to be updated on each new release
images:
- name: quay.io/cguertin14/k3supdater
  newTag: v1.1.2

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: k3supdater
