name: Release app

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          GIT_COMMIT=$(git rev-parse --short HEAD)
          GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          BUILD_TIME=$(date '+%FT%TZ')
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=git_commit::${GIT_COMMIT}
          echo ::set-output name=git_branch::${GIT_BRANCH}
          echo ::set-output name=build_time::${BUILD_TIME}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          version: latest

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Build and Push
        if: github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          build-args: | 
            VERSION=${{ steps.prep.outputs.version }}
            GIT_COMMIT=${{ steps.prep.outputs.git_commit }}
            GIT_BRANCH=${{ steps.prep.outputs.git_branch }}
            BUILD_TIME=${{ steps.prep.outputs.build_time }}
          context: ./
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            quay.io/cguertin14/k3supdater:${{ github.sha }}

      - name: Build and Push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          build-args: | 
            VERSION=${{ steps.prep.outputs.version }}
            GIT_COMMIT=${{ steps.prep.outputs.git_commit }}
            GIT_BRANCH=${{ steps.prep.outputs.git_branch }}
            BUILD_TIME=${{ steps.prep.outputs.build_time }}
          context: ./
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            quay.io/cguertin14/k3supdater:latest
            quay.io/cguertin14/k3supdater:${{ steps.prep.outputs.version }}